server:
  port: 80

spring:
  aop:
    auto: true
    proxy-target-class: false
  redis:
    database: 0
    host: 192.168.1.99
    password: 123456
    port: 6379
    timeout: 10000s
    jedis:
      pool:
        max-wait: -1s
        max-active: 20
        max-idle: 50
        min-idle: 0

    #cluster:
    #  nodes: 192.168.1.8
    #  max-redirects: 1

  profiles:
    active: dev
